package com.interframe.hr.repository.mybatis.model;

public class SysPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_PERMISSION.ID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_PERMISSION.LEVEL
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_PERMISSION.TYPE
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_PERMISSION.URL
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_PERMISSION.ACTION
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_PERMISSION.PARENT_ID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_PERMISSION.VALID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_PERMISSION.ID
     *
     * @return the value of HR.SYS_PERMISSION.ID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_PERMISSION.ID
     *
     * @param id the value for HR.SYS_PERMISSION.ID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_PERMISSION.LEVEL
     *
     * @return the value of HR.SYS_PERMISSION.LEVEL
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_PERMISSION.LEVEL
     *
     * @param level the value for HR.SYS_PERMISSION.LEVEL
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_PERMISSION.TYPE
     *
     * @return the value of HR.SYS_PERMISSION.TYPE
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_PERMISSION.TYPE
     *
     * @param type the value for HR.SYS_PERMISSION.TYPE
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_PERMISSION.URL
     *
     * @return the value of HR.SYS_PERMISSION.URL
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_PERMISSION.URL
     *
     * @param url the value for HR.SYS_PERMISSION.URL
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_PERMISSION.ACTION
     *
     * @return the value of HR.SYS_PERMISSION.ACTION
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_PERMISSION.ACTION
     *
     * @param action the value for HR.SYS_PERMISSION.ACTION
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_PERMISSION.PARENT_ID
     *
     * @return the value of HR.SYS_PERMISSION.PARENT_ID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_PERMISSION.PARENT_ID
     *
     * @param parentId the value for HR.SYS_PERMISSION.PARENT_ID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_PERMISSION.VALID
     *
     * @return the value of HR.SYS_PERMISSION.VALID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_PERMISSION.VALID
     *
     * @param valid the value for HR.SYS_PERMISSION.VALID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setValid(String valid) {
        this.valid = valid;
    }
}