package com.interframe.hr.repository.mybatis.model;

public class SysRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_ROLE.ID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_ROLE.NAME
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_ROLE.ID
     *
     * @return the value of HR.SYS_ROLE.ID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_ROLE.ID
     *
     * @param id the value for HR.SYS_ROLE.ID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_ROLE.NAME
     *
     * @return the value of HR.SYS_ROLE.NAME
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_ROLE.NAME
     *
     * @param name the value for HR.SYS_ROLE.NAME
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}