package com.interframe.hr.repository.mybatis.model;

public class SysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_USER.ID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_USER.NAME
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_USER.LOGIN_NAME
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_USER.PASSWORD
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.SYS_USER.VALID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    private String valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_USER.ID
     *
     * @return the value of HR.SYS_USER.ID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_USER.ID
     *
     * @param id the value for HR.SYS_USER.ID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_USER.NAME
     *
     * @return the value of HR.SYS_USER.NAME
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_USER.NAME
     *
     * @param name the value for HR.SYS_USER.NAME
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_USER.LOGIN_NAME
     *
     * @return the value of HR.SYS_USER.LOGIN_NAME
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_USER.LOGIN_NAME
     *
     * @param loginName the value for HR.SYS_USER.LOGIN_NAME
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_USER.PASSWORD
     *
     * @return the value of HR.SYS_USER.PASSWORD
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_USER.PASSWORD
     *
     * @param password the value for HR.SYS_USER.PASSWORD
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.SYS_USER.VALID
     *
     * @return the value of HR.SYS_USER.VALID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.SYS_USER.VALID
     *
     * @param valid the value for HR.SYS_USER.VALID
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    public void setValid(String valid) {
        this.valid = valid;
    }
}