package com.interframe.hr.repository.mybatis;

import com.interframe.hr.repository.mybatis.model.SysRole;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.SYS_ROLE
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.SYS_ROLE
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.SYS_ROLE
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.SYS_ROLE
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    SysRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.SYS_ROLE
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.SYS_ROLE
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    int updateByPrimaryKey(SysRole record);
}