package com.interframe.hr.repository.mybatis;

import org.springframework.stereotype.Repository;

import com.interframe.hr.repository.mybatis.model.SysUser;

@Repository
public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.SYS_USER
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.SYS_USER
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.SYS_USER
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.SYS_USER
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    SysUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.SYS_USER
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.SYS_USER
     *
     * @mbg.generated Mon Oct 10 16:33:46 CST 2016
     */
    int updateByPrimaryKey(SysUser record);
}